"""Type stubs for the freestiler Rust extension module."""

def _freestile(
    layers: list[dict],
    output_path: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    generate_ids: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
) -> str: ...

def _freestile_file(
    input_path: str,
    output_path: str,
    layer_name: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
) -> str: ...

def _freestile_duckdb(
    input_path: str,
    output_path: str,
    layer_name: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
) -> str: ...

def _freestile_duckdb_query(
    sql: str,
    db_path: str | None,
    output_path: str,
    layer_name: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
    streaming_mode: str,
) -> str: ...

def _freestile_postgis(
    conn_str: str,
    sql: str,
    output_path: str,
    layer_name: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
    batch_size: int | None,
    geom_column: str | None = None,
) -> str: ...

def _freestile_postgis_to_mongo(
    conn_str: str,
    sql: str,
    mongo_uri: str,
    mongo_db: str,
    mongo_collection: str,
    layer_name: str,
    tile_format: str,
    min_zoom: int,
    max_zoom: int,
    base_zoom: int,
    do_simplify: bool,
    quiet: bool,
    drop_rate: float,
    cluster_distance: float,
    cluster_maxzoom: int,
    do_coalesce: bool,
    batch_size: int | None,
    upsert: bool,
    geom_column: str | None = None,
    mongo_batch_size: int | None = None,
    mongo_write_concurrency: int | None = None,
    mongo_create_indexes: bool | None = None,
    force_large_mode: bool | None = None,
    large_mode_threshold: int | None = None,
    mongo_flush_min_tiles: int | None = None,
    mongo_flush_max_bytes: int | None = None,
    streaming: bool | None = None,
    mongo_profile: str | None = None,
) -> str: ...
