# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_freestiler_wrappers", use_symbols = TRUE, package_name = "freestiler")

#' @usage NULL
#' @useDynLib freestiler, .registration = TRUE
NULL

#' Create vector tiles from spatial data (multi-layer support)
#'
#' @param layers List of layer lists
#' @param output_path Path for output .pmtiles file
#' @param tile_format "mvt" or "mlt"
#' @param global_min_zoom Minimum zoom level
#' @param global_max_zoom Maximum zoom level
#' @param do_simplify Whether to simplify geometries at lower zooms
#' @param generate_ids Whether to generate sequential feature IDs
#' @param quiet Whether to suppress progress messages
#' @param drop_rate Exponential drop rate (negative = off)
#' @param cluster_distance Pixel distance for clustering (negative = off)
#' @param cluster_maxzoom Max zoom for clustering (negative = use max_zoom - 1)
#' @param do_coalesce Whether to coalesce features with same attributes
#' @return The output file path or an error message
#' @keywords internal
rust_freestile <- function(layers, output_path, tile_format, global_min_zoom, global_max_zoom, base_zoom, do_simplify, generate_ids, quiet, drop_rate, cluster_distance, cluster_maxzoom, do_coalesce) .Call(wrap__rust_freestile, layers, output_path, tile_format, global_min_zoom, global_max_zoom, base_zoom, do_simplify, generate_ids, quiet, drop_rate, cluster_distance, cluster_maxzoom, do_coalesce)


# nolint end
